"""Deleted Unused Colums

Revision ID: 1160ad22e164
Revises: 6877a22d9d91
Create Date: 2025-05-24 23:04:05.121879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1160ad22e164'
down_revision: Union[str, None] = '6877a22d9d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'ai_generated_plan_overview')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('ai_generated_plan_overview', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
