"""Deleted AiGenerated Table

Revision ID: 6877a22d9d91
Revises: 3adb8d258b55
Create Date: 2025-05-24 22:57:37.021391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6877a22d9d91'
down_revision: Union[str, None] = '3adb8d258b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_generated_content_id'), table_name='ai_generated_content')
    op.drop_table('ai_generated_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generated_content',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ai_generated_content_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_generated_content_pkey'))
    )
    op.create_index(op.f('ix_ai_generated_content_id'), 'ai_generated_content', ['id'], unique=False)
    # ### end Alembic commands ###
